[package]
name = "server"
version = "0.1.0"
authors = ["Martin Lofaj <lofajmatko@gmail.com>"]

[dependencies]
iron = "*"
router = "*"
persistent = "*"
bodyparser = "*"

uuid = { version = "*", features = ["v4"] }

serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"